baseURL: https://allen-liaoo.github.io/alblog/
languageCode: en-us
title: Allen's Corner of the World
theme: PaperMod
enableGitInfo: true

taxanomies:
  tags: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search