# math
defaultMarkdownHandler: goldmark
goldmark:
  renderer:
    unsafe: true
  extensions:
    passthrough:
      delimiters:
        block:
        - - \[
          - \]
        - - $$
          - $$
        inline:
        - - \(
          - \)
        - - $
          - $
      enable: true

# code
highlight:
  # anchorLineNos: true
  codeFences: true
  guessSyntax: true
  lineNos: true
  noClasses: false
  style: onedark 
  # style attr is useless
  # need to override assets/css/includes/chroma-styles.css

tableOfContents:
  startLevel: 2
  endLevel: 4