main:
  - identifier: about
    name: About
    pageRef: page/about.md
    weight: 10
  - identifier: posts
    name: Posts
    pageRef: page/archives.md
    weight: 20
  - identifier: tags
    name: Tags
    pageRef: /tags/
    weight: 30
  - identifier: search
    name: Search
    pageRef: page/search.md
    weight: 40