# theme params
defaultTheme: light
# disableThemeToggle: true
favicon: favicon.png
appleTouchIcon: favicon.png

# per post settings
editPost:
  URL: "https://github.com/allen-liaoo/alsblog/tree/HEAD/content"
  Text: "View Source" # edit text
  appendFilePath: true # to append file path to Edit link
comments: true
TocSide: left
showToc: true
TocOpen: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowReadingTime: true

# EnableInstantClick: true

# fuse.js search options
fuseOpts:
  shouldSort: true
  includeMatches: true
  threshold: 0.4 # fuzzy match
  ignoreLocation: true # search anywhere in below sections
  keys: ["title", "permalink", "summary", "content"]

assets:
  disableHLJS: true # disable papermod's highlight.js

# math mode on by default
math: true

socialIcons: # optional for home page mode (not on)
  - name: "Github"
    url: "https://github.com/allen-liaoo/"
  - name: "email"
    url: "mailto://wcliaw610@gmail.com"