[build.environment]
HUGO_VERSION = "0.125.5"
TZ = "America/Chicago"

[build]
publish = "public"
command = "hugo --gc"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://giscus.app"